---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: goapp-backend
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: goapp-backend
        tier: backend
    spec:
      containers:
        - name: goapp-backend
          image: "arsharaf/backend:0.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: goapp-backend
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http